### ISSUE TITLE
Problem with installation after unsuccessful removal.

### ISSUE THREAD

**Issue by azz1803** [Alex-Rose/fb-messenger-cli#138]
I've copied the package.json to my System32 folder and run the npm install fb-messenger-cli command. There were some warnings, and it didn't function appropriately so I wanted to re-install the package and try again. However, now it'd seem I cannot 'fully' uninstall the package as this is what I'm getting when trying to install again:

![image](https://user-images.githubusercontent.com/9116897/34649546-2dc27550-f3a9-11e7-8c00-5aa4bf5b337c.png)

Any suggestions as to how to resolve this would be massively appreciated.

**Comment by SamBergeron** [comment]
You need to put the -g argument (`npm install -g fb-messenger-cli`) to install a package globally.
if you don't add the `-g` you just create a folder name "fb-messenger-cli" in the current directory that contains the project (you can run it from there if you want)

You're getting this error because you're trying to install the package inside a directory that is already called the "fb-messenger-cli" (essentially you trying to install it as a dependency to itself)

Try either deleting the fb-messenger-cli directory and installing locally, or just installing globally with -g
