### ISSUE TITLE
env: node\r: No such file or directory Error

### ISSUE THREAD

**Issue by whitef0x0** [Alex-Rose/fb-messenger-cli#16]
I'm getting this `env: node\r: No such file or directory` (see https://github.com/nwjs/nw-builder/issues/75 for context) running this on MacOS El Capitan with Node 6.5.0. 

Can you change the line endings to be compatible?

**Comment by SamBergeron** [comment]
Alright I removed the shebang line in cli.js, it was pretty useless anyways since we're calling node directly anyways. 
You mind reinstalling with npm and giving it a whirl?

**Comment by SamBergeron** [comment]
Holy crap this gave me a lot of issues, but I was pretty determined to fix it this time. 
Turns out, saving a with the line endings doesn't matter, git fixes them anyways. But if you build the npm tarball on Windows, it saves to npm with windows line-endings. Hence this being a problem. Took me a while to figure it out. 

Please try re-installing with npm globally, it should work with version 1.2.7. Let me know.
