### ISSUE TITLE
Asks To Login Twice Before Working

### ISSUE THREAD

**Issue by Noah-Huppert** [Alex-Rose/fb-messenger-cli#170]
When I first launched fb-messenger-cli it asked me to enter my credentials twice before logging in. The first time it said "Login verification failed", then I entered the exact same credentials and it worked:

```
~ ❯ sudo fb-messenger-cli
Login verification failed: Warning: Settings not found, saving default values
Facebook credentials:
Email: REDACTED
Password: REDACTED
Attempting login...
Login verification failed: No saved profile, please login
Facebook credentials:
Email: REDACTED
Password: REDACTED
Attempting login...
Settings have been saved
Waiting 20 seconds for login page
^[[A^[[AWaiting 20 seconds for login page
Saving to crypt {"cookie":"xs=REDACTED; sb=REDACTED; datr=REDACTED; c_user=REDACTED; wd=800x600","fb_dtsg":"REDACTED","c_user":"REDACTED","saveTime":1525807310709}
(node:1898) Warning: Use Cipheriv for counter mode of aes-256-ctr
Launching app...
Saving to crypt {"cookie":"xs=REDACTED; sb=REDACTED; datr=REDACTED; c_user=REDACTED; wd=800x600","fb_dtsg":"REDACTED","c_user":"REDACTED","saveTime":1525807310846}
(node:1898) Warning: Use Cipheriv for counter mode of aes-256-ctr
Fetching conversations...
Launching app...
```

If I don't launch it with sudo I get the same thing but after the second round of entering credentials I get a "Login verification failed" error a permission message:

```
Login verification failed: Error: EACCES: permission denied, open '/usr/local/li
b/node_modules/fb-messenger-cli/.kryptonite'
```

**Comment by toufikbelouadah** [comment]
me timesout weired behaviour https://github.com/Alex-Rose/fb-messenger-cli/issues/177 ><

**Comment by SamBergeron** [comment]
@Noah-Huppert if you installed it using `sudo npm install -g` you need root permissions to create and modify the `.settings` file we use to save your settings. Subsequently you don't need root permissions because you don't modify that file anymore.

You can install it without using sudo and you won't need it.
Also we now create a default settings file on install, because a lot of people were annoyed with this, you can update to version 2.1.0 and it should be alright.
Sorry it took forever.
